# Activity File for Portland, OR

```{r chunk1, eval = TRUE, echo = TRUE, results = "show", warning = TRUE, error = TRUE, message = TRUE, fig.width = 8}
#getwd()
#setwd("C:/Users/Richard Buote/Desktop/Trip Data USA/")
#install.packages("dplyr")
#install.packages("data.table")
library(lubridate)
library(stringr)
library(data.table)
library(dplyr)
library(car)
library(kimisc)
```

```{r chunk2, eval = TRUE, echo = TRUE, results = "show", warning = TRUE, error = TRUE, message = TRUE, fig.width = 8}
trippub <- "~/NHTS/data/trippub.csv"
```

# Read .CSV
# New data, only Portland
# New age group, young and old
```{r chunk3, eval = TRUE, echo = TRUE, results = "show", warning = TRUE, error = TRUE, message = TRUE, fig.width = 8}
personaltrips <- read.csv2(trippub, header = TRUE, sep = ",")
portlanddata <- personaltrips[which (personaltrips$HH_CBSA == 38900),]
portlanddata$agegroup <- ifelse(portlanddata$R_AGE <= 18, 0, 1)
```

# Calculate active minutes (transit minutes divided by 2)
```{r chunk4, eval = TRUE, echo = TRUE, results = "show", warning = TRUE, error = TRUE, message = TRUE, fig.width = 8}

portlanddata$transitminutes <- if_else(portlanddata$TRPTRANS %in% c(11,15,16), portlanddata$TRVLCMIN/2, ifelse(portlanddata$TRPTRANS %in% c(1,2), portlanddata$TRVLCMIN*1, 0))
```
# Aggregate data
# Aggregating aggregatedportland by agegroup
```{r chunk5, eval = TRUE, echo = TRUE, results = "show", warning = TRUE, error = TRUE, message = TRUE, fig.width = 8}

aggregatedportland <- portlanddata %>%
  group_by(HOUSEID, PERSONID) %>%
  summarise(agegroup = first(agegroup),
            transitminutes = sum(transitminutes))


summaryData <- cbind(
  aggregate(
    aggregatedportland[, "transitminutes"],
    by = list(agegroup = aggregatedportland$agegroup),
    FUN = mean,
    na.rm = FALSE
  ),
  aggregate(
    aggregatedportland[, "transitminutes"],
    by = list(agegroup = aggregatedportland$agegroup),
    FUN = sd,
    na.rm = FALSE
  )[, 2]
)

colnames(summaryData) <- c("agegroup", "mean", "sd")

summaryData$proportion <- NA

agegroups <- unique(aggregatedportland$agegroup)

for (i in 1:length(agegroups)) {
  tempdata <- aggregatedportland[which(aggregatedportland$agegroup == agegroups[i]), ]
  summaryData[i, "proportion"] <- length(which(tempdata$transitminutes > 0))  / nrow(tempdata)
}
```
